import { Transaction, Contact, SecurityAlert, TrustedDevice } from '../types';

export const INITIAL_USER = {
  name: 'Sujan Kumar',
  email: 'sujan.kumar@example.com',
  phone: '+91 98765 00000',
  balance: 42500,
  safetyScore: 94,
  protectionLevel: 'High Protection' as const,
  notificationsEnabled: true,
};

export const INITIAL_CONTACTS: Omit<Contact, 'userId'>[] = [
  { id: 'c1', name: 'Rahul Kumar', phone: '+91 98765 43210', isFavorite: true, isNew: false, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150' },
  { id: 'c2', name: 'Priya Sharma', phone: '+91 98123 45678', isFavorite: true, isNew: false, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150' },
  { id: 'c3', name: 'Ankit Patel', phone: '+91 97111 22334', isFavorite: false, isNew: false, avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150' },
  { id: 'c4', name: 'Mom', phone: '+91 99000 11223', isFavorite: true, isNew: false, avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150' },
  { id: 'c5', name: 'Fresh Mart QR', phone: '+91 98000 77665', isFavorite: false, isNew: true, avatar: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?w=150' },
];

export const INITIAL_TRANSACTIONS: Omit<Transaction, 'userId'>[] = [
  {
    id: 'tx-101',
    recipientName: 'Coffee Shop',
    recipientPhone: '+91 98000 11111',
    amount: 250,
    note: 'Morning Mocha',
    category: 'Food & Dining',
    type: 'QR',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 96,
    riskLevel: 'LOW',
    reasons: ['Normal merchant payment', 'Recognized location', 'Low transaction amount'],
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 mins ago
    technicalDetails: {
      rfScore: 0.02,
      ifScore: 0.05,
      graphRisk: 0.01,
      shapFactors: [{ factor: 'Low Spend Envelope', impact: '-0.40', weight: -0.40 }],
      riskFusionModel: 'SentinelFin Baseline Protection',
      anomaliesDetected: [],
    },
  },
  {
    id: 'tx-102',
    recipientName: 'Rahul Kumar',
    recipientPhone: '+91 98765 43210',
    amount: 1500,
    note: 'Dinner split',
    category: 'Transfers',
    type: 'PHONE',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 92,
    riskLevel: 'LOW',
    reasons: ['Frequent recipient contact', 'Normal transfer velocity', 'Trusted device'],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), // 3 hours ago
    technicalDetails: {
      rfScore: 0.05,
      ifScore: 0.08,
      graphRisk: 0.03,
      shapFactors: [{ factor: 'Frequent Contact Edge', impact: '-0.32', weight: -0.32 }],
      riskFusionModel: 'SentinelFin Multi-Factor Risk Fusion',
      anomaliesDetected: [],
    },
  },
  {
    id: 'tx-103',
    recipientName: 'Electricity Board',
    recipientPhone: '+91 98000 22222',
    amount: 1200,
    note: 'Monthly Utility',
    category: 'Bills & Utilities',
    type: 'CONTACT',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 98,
    riskLevel: 'LOW',
    reasons: ['Verified biller', 'Regular monthly recurring pattern', 'Low risk entity'],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // Yesterday
    technicalDetails: {
      rfScore: 0.01,
      ifScore: 0.02,
      graphRisk: 0.01,
      shapFactors: [{ factor: 'Recurring Bill Match', impact: '-0.45', weight: -0.45 }],
      riskFusionModel: 'SentinelFin Baseline Protection',
      anomaliesDetected: [],
    },
  },
  {
    id: 'tx-105',
    recipientName: 'Mega Electronics Store',
    recipientPhone: '+91 98000 33333',
    amount: 11200,
    note: 'Smartwatch & Accessories',
    category: 'Shopping',
    type: 'QR',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 90,
    riskLevel: 'LOW',
    reasons: ['Verified retail merchant', 'POS Terminal match', 'Within high protection limit'],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hrs ago
    technicalDetails: {
      rfScore: 0.08,
      ifScore: 0.12,
      graphRisk: 0.04,
      shapFactors: [{ factor: 'Retail Merchant Certificate', impact: '-0.25', weight: -0.25 }],
      riskFusionModel: 'SentinelFin Multi-Factor Risk Fusion',
      anomaliesDetected: [],
    },
  },
  {
    id: 'tx-104',
    recipientName: 'Unknown Account',
    recipientPhone: '+91 99999 88888',
    amount: 84500,
    note: 'Urgent Wire',
    category: 'Transfers',
    type: 'PHONE',
    status: 'BLOCKED',
    decision: 'BLOCK',
    safetyScore: 18,
    riskLevel: 'CRITICAL',
    reasons: [
      'This payment is much larger than your usual payments.',
      'This recipient is unfamiliar and has no transaction history with you.',
      'An unfamiliar device context was detected during transfer request.',
      'Additional high-confidence threat signals were flagged by SentinelFin.',
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    technicalDetails: {
      rfScore: 0.94,
      ifScore: 0.88,
      graphRisk: 0.82,
      shapFactors: [
        { factor: 'Transfer Amount Magnitude', impact: '+0.42', weight: 0.42 },
        { factor: 'Unrecognized Graph Node', impact: '+0.31', weight: 0.31 },
        { factor: 'Anomaly Outlier Score', impact: '+0.21', weight: 0.21 },
      ],
      riskFusionModel: 'Ensembled Random Forest + Isolation Forest + Neo4j Graph Fusion',
      anomaliesDetected: [
        'Out-of-distribution transfer magnitude (₹84,500 vs ₹1,500 avg)',
        'Unrecognized destination vertex in knowledge graph',
        'Device fingerprint mismatch',
      ],
    },
  },
  {
    id: 'tx-106',
    recipientName: 'FastWire Pay Ltd',
    recipientPhone: '+91 99888 77766',
    amount: 9800,
    note: 'Consulting Batch 1',
    category: 'Transfers',
    type: 'PHONE',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 88,
    riskLevel: 'MEDIUM',
    reasons: ['Within standard limits', 'Verified VPA format'],
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
  },
  {
    id: 'tx-107',
    recipientName: 'FastWire Pay Ltd',
    recipientPhone: '+91 99888 77766',
    amount: 9800,
    note: 'Consulting Batch 2',
    category: 'Transfers',
    type: 'PHONE',
    status: 'COMPLETED',
    decision: 'ALLOW',
    safetyScore: 82,
    riskLevel: 'MEDIUM',
    reasons: ['Within standard limits', 'Rapid transfer frequency detected'],
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1 hour ago
  },
  {
    id: 'tx-108',
    recipientName: 'FastWire Pay Ltd',
    recipientPhone: '+91 99888 77766',
    amount: 9800,
    note: 'Consulting Batch 3',
    category: 'Transfers',
    type: 'PHONE',
    status: 'COMPLETED',
    decision: 'CHALLENGE',
    safetyScore: 45,
    riskLevel: 'HIGH',
    reasons: ['Rapid consecutive transfers within 2 hours', 'Structuring near limit detected'],
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 mins ago
  },
];

export const INITIAL_ALERTS: Omit<SecurityAlert, 'userId'>[] = [
  {
    id: 'alt-1',
    title: 'Payment Stopped',
    message: 'SentinelFin stopped a suspicious payment of ₹84,500 to an unknown recipient.',
    severity: 'critical',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    isRead: false,
    relatedTransactionId: 'tx-104',
    actionTaken: 'Payment Blocked Automatically',
  },
  {
    id: 'alt-2',
    title: 'New Device Recognized',
    message: 'Chrome browser on Linux was recognized and added to your trusted devices.',
    severity: 'low',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    isRead: true,
  },
];

export const INITIAL_DEVICES: Omit<TrustedDevice, 'userId'>[] = [
  {
    id: 'dev-1',
    name: 'Chrome on Windows',
    browser: 'Chrome 122',
    isCurrent: true,
    isTrusted: true,
    lastActive: 'Active now',
    location: 'Bengaluru, KA, India',
  },
];
